### ISSUE TITLE
Not Getting Action to Trigger Network Request

### ISSUE THREAD

**Issue by andresberejnoi** [jasonelle-archive/jasonelle-v2#72] opened 2019-11-09 02:46 UTC
**Problem Description** 
Hello, first of all, thank you for maintaining and develop this technology. I was inmediately intrigued to see how it works when I learned about it. 
I am writing because of an issue I am facing a problem implementing Jasonette on Android. However, I am not sure if my problems are caused by myself or bugs in the code. There are multiple things not working but please let me know if I should open individual issues for each.

The main issue is that I can't get actions to work. This is all on Android by making changes to the jasonette repository and installing the APK with Android Studio. 
I have another minor problem about icons for the footer tabs and displaying as a solid box instead of the icons I included.
I am running a Python Flask server to serve the json text using Flask's jsonify module on the default root flask endpoint.
I am writing the json objects as Python dictionaries since they have the same structure (this assumes that Jasonette does not care about the order of the Json components).

 Acctions Don't Seem to Work
    I am trying to submit a login request to a site. My knowledge of network requests, HTTP requests and anything related is very limited so I could be making a simple mistake here. My issue is that I defined an action under the "actions" tag in the "head" component to send a post request to my Flask server as a test. The flask server simply takes the request and prints the information sent to it (a fake email and password). I tried different ways of triggering the request but I don't remember what I tried before. What I am currently doing is adding a trigger action in the menu icon at the top right of the header bar.
When I click on the button nothing happens and my Flask server does not receive any request to my fake login endpoint. 

**Screenshots** 
This is a gif of my app currently in case it helps. I was also writing another issue about the offline message but I have partially solved it for now. 
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/17301409/68521256-8a34e780-029f-11ea-9f6d-0b491d6635e0.gif)

You can also see that on the center footer tab "Reportes" the icon is just a solid box when in fact it is a png icon with transparent background but for some reason gets displayed as a solid color. This is in contrast with the "more" tab which has three dots with transparent background. I made the two icons with a similar process so I don't get why one works and the other does not. Notice that the first tab icon for "Find my Car" is using an icon from one example I found in the Jasonette repositories, so the icon is retrieved from a URL while mine are included inside the APK.  I will add the two icons below:
dots_icon.png
![dots_icon](https://user-images.githubusercontent.com/17301409/68521369-b1d87f80-02a0-11ea-8b2a-0ecb2f12304f.png)
reports_icon.png
![report_icon](https://user-images.githubusercontent.com/17301409/68521370-b1d87f80-02a0-11ea-813d-c94c4adc9dac.png)

**Sample Code**
I will try to write here how my actions are defined but if it is not clear please let me know if I should include a small repository with all the code needed to run a minimum example.

In the head component I define an action for network request. Notice that for "url" there is a Python variable URL_BASE which simply contains the current address to my flask server
```
"head": {
    ...
    "actions": {
        ...
        "fake_login": { 
            "type":"$network.request",
            "options":{
                "url":URL_BASE + "/fake_login",
                "method":"post",
                "data":{
                    "email":"email@email.test",
                    "password":"MyPassword12345!"
                },
                "content_type": "json",
            },
            "success":{
                "type":"$network.success"
            }
        }
    ...
    }
```

Then I attached a trigger action to my menu:
```
"body": {

"header": {
    "title":"Síguelo",
    "menu":{
        "image":"file://menu_icon.png",
        "action":{
            "trigger":"fake_login"
        }
    }
}

...
}
```

**Futher Context**
If there is any information missing that I should include please let me know. I will now open some other issues in order to not clutter this one. 
Thanks for your time

**Comment by andresberejnoi** [comment] 2019-11-10 04:51
I even tried many of the examples in the documentation to no avail. I attached a simple action to my menu button directly from the docs like the following example:
```
{
  "head": {
    ...
  },
  "body": {
    "header": {
      "menu": {
        "text": "Press me",
        "action": {
          "type": "$util.alert",
          "options": {
            "title": "Good job!",
            "description": "You know how to press a button!"
          }
        }
      }
    },
    ...
  }
}
```
When I click on menu I don't get any kind of banner or any indication the app is doing anything.

I also tried putting actions in a button located in a components sections like `body.sections[0].items[0].components` and still nothing happens (I used an inline action). There is just a built-in sound indicating the button was pressed,but nothing happens and my Flask server does not register any request sent to it.

**Comment by andresberejnoi** [comment] 2019-11-10 05:43
I was thinking that maybe I need to activate the ability to use actions from the APK? Maybe it's something that needs to be uncommented before building the app in Android Studio, similar to how the Google Maps API comes commented out. Is there something like that here or should actions work by default?

**Comment by andresberejnoi** [comment] 2019-11-11 16:41
Just in case someone reads this, I have not solved the problem but at least found more specific situations when $actions don't work.
If I compile the app into an APK with Android Studio and point it to my my Flask server to stream json, then actions don't work at all. However, if I use the Jason app for prototyping (the one that allows to enter different urls to quickly test projects) then my program works and actions do get triggered. Could there be a setting in Android studio that I need to turn on?

**Comment by clsource** [comment] 2019-11-11 21:48
Hello @andresberejnoi 
Please @panterozo or @christianswanepoel take a look into this :) thanks.

**Comment by andresberejnoi** [comment] 2019-11-20 13:46
I was thinking that maybe streaming the json code over http was not working correctly so I modified the APK to use only local files with the "file://..." syntax. However, this did not solve the problem. Actions are still not working and I still have the same problem as before, where I get an "offline" message when switching from one view to another and coming back. 

That last behaviour is inconsistent, though. There are times when I go to another tab and come back and the page is still there and I do it a couple more times and it happens only then. After it happens, the only way to get the page back to normal is to kill the app completely and then launching it again.

Did anyone experience anything like this or knows how I can fix it? I don't want all this time to go to waste and have to abandon this project. Right now the only way I get actions to work is by using the test jason app.

**Comment by clsource** [comment] 2019-11-20 14:53
@andresberejnoi I believe this is something related to the syntax of the json. Could you share a complete example json that you are using so we can detect any possible errors.

Please refer to for an example login app.
https://github.com/jasonelle/docs/blob/develop/examples/jasonette/apps/token-authentication-example/public/login.json

Note that code contains something like `"url": "ROOT/users/sign_in.json",` That `ROOT` should be replace it with a full url. Example `"url": "https://mysite.com/users/sign_in.json"`.

**Comment by andresberejnoi** [comment] 2019-11-20 15:06
Thank you for replying. I'll go produce a sample file without some
sensitive information and add it here.
Also I'm actually using the login page example but modified to point to my
server and with the corresponding fields.
The reason I'm not sure that it's a syntax problem with json is that all
those actions work properly with the prototyping jason app. I can actually
send network requests with no problem, login to my server, display banners,
alerts and all of those work as expected. It's only when I compile the APK
myself (whether streaming json over http or over local files) that it
doesn't work.

**Comment by andresberejnoi** [comment] 2019-11-21 05:02
Here I'm adding the three different pages that I am using for my app. I removed a few things but everything should probably work the same as what I am using. Notice that I replaced my server ip at the url addresses with some string since I don't know if that is sensitive information to share here

First view is **main_page.json** : 
```
{
   "$jason": {
      "head": {
         "title": "S\u00edguelo",
         "description": "App to monitor your car with GPS tracking",
         "icon": "file://TraccarAppLogo.png",
         "actions": {
            "$foreground": {
               "type": "$reload"
            },
            "$pull": {
               "type": "$flush",
               "success": {
                  "type": "$reload"
               }
            },
            "fake_login": {
               "type": "$network.request",
               "options": {
                  "url": "<my_fake_server>/fake_login",
                  "method": "post",
                  "data": {
                     "email": "email@email.test",
                     "password": "MyPassword12345!"
                  }
               },
               "success": {
                  "type": "$util.alert",
                  "options": {
                     "title": "Fake Login Success",
                     "description": "{{$jason}}"
                  }
               },
               "error": {
                  "type": "$util.aler",
                  "options": {
                     "title": "Error",
                     "description": "Something happened"
                  }
               }
            },
            "fetch_location": {
               "type": "$network.request",
               "options": {
                  "url": "<my_fake_server>/fetch_location",
                  "method": "get",
                  "header": {
                     "Authorization": "Basic {{JSON.stringify($global.email:$global.password)}}",
                     "OTHER": "{{$global.email}}"
                  }
               },
               "success": {
                  "type": "$cache.set",
                  "options": {
                     "items": "{{$jason}}"
                  },
                  "success": {
                     "type": "$util.alert",
                     "options": {
                        "title": "Location fetched",
                        "description": "{{$cache.items.latitude}},{{$cache.items.longitude}}"
                     }
                  }
               },
               "error": {
                  "type": "$util.banner",
                  "options": {
                     "title": "Error Occurred",
                     "description": "ERROR"
                  }
               }
            }
         }
      },
      "body": {
         "header": {
            "title": "S\u00edguelo",
            "menu": {
               "image": "file://menu_icon.png",
               "action": {
                  "type": "$util.alert",
                  "options": {
                     "title": "Good job!",
                     "description": "You know how to press a button!"
                  }
               }
            }
         },
         "sections": [
            {
               "header": {
                  "type": "label",
                  "style": {
                     "background": "#f5f5f5"
                  },
                  "text": "Mapa"
               },
               "items": [
                  {
                     "type": "map",
                     "region": {
                        "coord": "-20.783312, 30.182129",
                        "width": "2000",
                        "height": "2000"
                     },
                     "pins": [
                        {
                           "title": "I am a pin",
                           "description": "Still a pin...",
                           "coord": "-20.783312, 30.182129"
                        }
                     ],
                     "style": {
                        "width": "100%",
                        "height": "100%"
                     }
                  }
               ]
            }
         ],
         "layers": [
            {
               "type": "image",
               "url": "file://TraccarAppLogo_green_bg.png",
               "style": {
                  "width": "60",
                  "corner_radius": "50",
                  "bottom": "70",
                  "right": "20"
               },
               "action": {
                  "trigger": "fetch_location"
               }
            },
            {
               "type": "image",
               "url": "file://car_icon.png",
               "style": {
                  "width": "60",
                  "corner_radius": "50",
                  "bottom": "70",
                  "right": "100"
               },
               "action": {
                  "trigger": "fetch_location"
               }
            }
         ],
         "footer": {
            "tabs": {
               "style": {
                  "background": "rgba(255,255,255,0.8)",
                  "color:disabled": "#cecece",
                  "color": "#009efa"
               },
               "items": [
                  {
                     "image": "file://car_icon.png",
                     "text": "Find Car",
                     "style": {
                        "height": "21"
                     },
                     "url": "file://main_page.json"
                  },
                  {
                     "image": "file://report_icon.png",
                     "text": "Reportes",
                     "style": {
                        "height": "21"
                     },
                     "href": {
                        "url": "file://reports_page.json"
                     }
                  },
                  {
                     "image": "file://dots_icon.png",
                     "text": "Login",
                     "style": {
                        "height": "21"
                     },
                     "url": "file://login_page.json"
                  },
                  {
                     "image": "https://raw.githubusercontent.com/Jasonette/Twitter-UI-example/master/images/me.png",
                     "text": "Jasonpedia",
                     "style": {
                        "height": "21"
                     },
                     "url": "https://raw.githubusercontent.com/Jasonette/Jasonpedia/gh-pages/hello.json"
                  }
               ]
            }
         }
      }
   }
}

```

Next view is **reports_page.json** (this one has two large icons to test things):
```
{
   "$jason": {
      "head": {
         "title": "Report Page",
         "actions": {
            "$foreground": {
               "type": "$reload"
            },
            "$pull": {
               "type": "$flush",
               "success": {
                  "type": "$reload"
               }
            },
            "fake_login": {
               "type": "$network.request",
               "options": {
                  "url": "<my_fake_server>/fake_login",
                  "method": "post",
                  "data": {
                     "email": "email@email.test",
                     "password": "MyPassword12345!"
                  }
               },
               "success": {
                  "type": "$util.alert",
                  "options": {
                     "title": "Fake Login Success",
                     "description": "{{$jason}}"
                  }
               },
               "error": {
                  "type": "$util.aler",
                  "options": {
                     "title": "Error",
                     "description": "Something happened"
                  }
               }
            }
         }
      },
      "body": {
         "header": {
            "title": "Reportes",
            "menu": {
               "image": "file://menu_icon.png"
            }
         },
         "sections": [
            {
               "items": [
                  {
                     "type": "vertical",
                     "components": [
                        {
                           "type": "button",
                           "url": "file://report_icon.png",
                           "style": {
                              "width": "148",
                              "height": "148",
                              "background": "#00ff00",
                              "color": "#ffffff",
                              "font": "HelveticaNeue",
                              "size": "12",
                              "corner_radius": "25"
                           },
                           "action": {
                              "type": "$util.alert",
                              "options": {
                                 "title": "Good job!",
                                 "description": "You know how to press a button!"
                              }
                           }
                        },
                        {
                           "type": "button",
                           "url": "file://car_icon.png",
                           "action": {
                              "trigger": "fake_login"
                           }
                        }
                     ]
                  }
               ]
            }
         ],
         "footer": {
            "tabs": {
               "style": {
                  "background": "rgba(255,255,255,0.8)",
                  "color:disabled": "#cecece",
                  "color": "#009efa"
               },
               "items": [
                  {
                     "image": "file://car_icon.png",
                     "text": "Find Car",
                     "style": {
                        "height": "21"
                     },
                     "url": "file://main_page.json"
                  },
                  {
                     "image": "file://report_icon.png",
                     "text": "Reportes",
                     "style": {
                        "height": "21"
                     },
                     "href": {
                        "url": "file://reports_page.json"
                     }
                  },
                  {
                     "image": "file://dots_icon.png",
                     "text": "Login",
                     "style": {
                        "height": "21"
                     },
                     "url": "file://login_page.json"
                  },
                  {
                     "image": "https://raw.githubusercontent.com/Jasonette/Twitter-UI-example/master/images/me.png",
                     "text": "Jasonpedia",
                     "style": {
                        "height": "21"
                     },
                     "url": "https://raw.githubusercontent.com/Jasonette/Jasonpedia/gh-pages/hello.json"
                  }
               ]
            }
         }
      }
   }
}

```

Finally, there is **login_page.json** (I modified the sign in section but did not touch or used the sign up section): 
```
{
   "$jason": {
      "head": {
         "title": "login"
      },
      "body": {
         "style": {
            "border": "none",
            "background": "#ffffff"
         },
         "header": {
            "title": "Sign in",
            "style": {
               "background": "#646464",
               "color": "#afffff"
            }
         },
         "sections": [
            {
               "items": [
                  {
                     "type": "space",
                     "height": "10"
                  },
                  {
                     "type": "textfield",
                     "name": "email",
                     "style": {
                        "size": "20",
                        "color": "#8bb92d",
                        "font": "HelveticaNeue-Bold",
                        "background": "#cecece",
                        "padding": "20"
                     },
                     "placeholder": "enter email"
                  },
                  {
                     "type": "space",
                     "height": "5"
                  },
                  {
                     "type": "textfield",
                     "name": "password",
                     "placeholder": "enter password",
                     "style": {
                        "size": "20",
                        "color": "#8bb92d",
                        "font": "HelveticaNeue-Bold",
                        "background": "#cecece",
                        "padding": "20",
                        "secure": "true"
                     }
                  },
                  {
                     "type": "space",
                     "height": "5"
                  },
                  {
                     "type": "label",
                     "style": {
                        "width": "100%",
                        "align": "right",
                        "font": "HelveticaNeue-Bold",
                        "size": "20",
                        "padding": "10",
                        "background": "#8bb92d",
                        "color": "#ffffff"
                     },
                     "text": "Sign in >",
                     "action": {
                        "type": "$network.request",
                        "options": {
                           "url": "<my_fake_server>/api/session",
                           "method": "post",
                           "data": {
                              "email": "{{$get.email}}",
                              "password": "{{$get.password}}"
                           }
                        },
                        "success": {
                           "type": "$global.set",
                           "options": {
                              "email": "{{$jason.email}}",
                              "password": "{{$jason.password}}",
                              "token": "{{$jason.token}}"
                           },
                           "success": {
                              "type": "$util.alert",
                              "options": {
                                 "title": "Successful Login",
                                 "description": "User token: {{$global.token}}\nBasic {{btoa($global.email)}}:{{$global.password}}"
                              }
                           }
                        },
                        "error": {
                           "type": "$util.banner",
                           "options": {
                              "title": "Error",
                              "description": "Check that username and password are correct"
                           }
                        }
                     }
                  },
                  {
                     "type": "label",
                     "style": {
                        "size": "16",
                        "font": "HelveticaNeue-Bold",
                        "text": "or",
                        "padding": "10",
                        "align": "center"
                     }
                  },
                  {
                     "type": "label",
                     "text": "Sign up >",
                     "style": {
                        "align": "right",
                        "size": "20",
                        "padding": "10",
                        "font": "HelveticaNeue-Bold",
                        "background": "#8bb92d",
                        "color": "#ffffff"
                     },
                     "action": {
                        "type": "$network.request",
                        "options": {
                           "url": "ROOT/users.json",
                           "method": "post",
                           "data": {
                              "user[email]": "{{$get.email}}",
                              "user[password]": "{{$get.password}}"
                           }
                        },
                        "success": {
                           "type": "$session.set",
                           "options": {
                              "domain": "ROOT",
                              "header": {
                                 "X-User-Email": "{{$jason.email}}",
                                 "X-User-Token": "{{$jason.authentication_token}}"
                              }
                           },
                           "success": {
                              "type": "$href",
                              "options": {
                                 "url": "ROOT/posts.json",
                                 "transition": "replace"
                              }
                           }
                        },
                        "error": {
                           "type": "$util.banner",
                           "options": {
                              "title": "Enter credentials",
                              "description": "Please enter both email and password"
                           }
                        }
                     }
                  }
               ]
            }
         ]
      }
   }
}

```

Below are the icons used for buttons and layers: 

car_icon.png
![car_icon](https://user-images.githubusercontent.com/17301409/69304876-9fdbd280-0bf8-11ea-8052-417466afbb2d.png)

dots_icon.png
![dots_icon](https://user-images.githubusercontent.com/17301409/69304920-c00b9180-0bf8-11ea-8143-a6b1ea1f5397.png)

menu_icon.png
![menu_icon](https://user-images.githubusercontent.com/17301409/69304933-c8fc6300-0bf8-11ea-99cd-c59027c80514.png)

report_icon.png
![report_icon](https://user-images.githubusercontent.com/17301409/69304948-d44f8e80-0bf8-11ea-9006-0501a5128a0d.png)

TraccarAppLogo_green_bg.png
![TraccarAppLogo_green_bg](https://user-images.githubusercontent.com/17301409/69304973-e8938b80-0bf8-11ea-8c29-c07d656c7a44.png)

TraccarAppLogo.png
![TraccarAppLogo](https://user-images.githubusercontent.com/17301409/69304990-f0533000-0bf8-11ea-88f9-64998e81b507.png)


The json files I just shared above are configured with the "file://" syntax so they should all be included in the APK along with the icons. The first point of access I am using is "file://main_page.json" for when the app loads. 

There is another issue that may be related to this. As I understand from the docs, we can include simple in-line javascript into Jasonelle but when I tried it did not work. I may be doing it wrong. To see those parts check the fake login where I tried using the javascript built-in "btoa" function for base64 encoding. When it prints those parts I get the literal text I typed (all the "{{btoa($....." gets printed on the message. And this issue happens with my APK and with the prototyping jason app as well.

Let me know if there is something else I can provide that can give some insight.

**Comment by andresberejnoi** [comment] 2019-11-26 13:15
Well, as an update on this issue, it just occurred to me to try and download the repository again and compile the APK as is. In this case, all actions that I tested from Jasonpedia seemed to work. Then I added all my app json files to work locally and it almost worked. 

This time most actions on my application work. If I press a button with a banner I get it to pop up. However, network requests are still not working. I press buttons to send login requests to my flask server and it always goes to the error clause of the action, but never to the success clause. I know the endpoint is correct because I manually made that request from a linux terminal and got flask to respond and send the appropriate data.

This time the problem has extended: I cannot stream the app over http when changing the url in "strings.xml" to my flask server:

```
<resources>
    <string name="app_name">Siguelo-TEST</string>
    <string name="url">http://192.168.0.15:5000</string>
    <string name="launch">file://preload.json</string>
</resources>
``` 
The previous APK I compiled was able to reach my server and load the views easily but now I just get an offline message. This all makes me think that there is a setting that I need to activate.


I am not sure what changed regarding the Android studio project. I did all the same steps as before. I changed the app name in the "strings.xml" document and then uncommented the permisions to use maps and added my keys, and that's about it. My json code also has not changed.

I would appreciate if someone has any idea or tip about what I can do.

**Comment by panterozo** [comment] 2019-11-27 05:08
Hi @andresberejnoi .. I was looking your work, and is awesome that you join us to build new apps with this point of view. I hope I can help you.

About your last comment, you should consider a network communication between your phone and your own server. You should check if the phone "see" the ip address "192.168.0.1". Maybe, the previous version of your Jasonelle was, for some reason, watching this ip address. Maybe your tests changes between both versions. 

I tested your files locally, with the *file://* aproach and everything works fine. The only thing that I didn't test locally was the "post" method, but I get it later pointing to a dummy web page.

Does your app works if you put a online an public website in your jason?.. For example:

```
<resources>
    <string name="app_name">Siguelo-TEST</string>
    <string name="url">https://base.jasonelle.com/items/d12329cc/</string>
    <string name="launch">file://preload.json</string>
</resources>
```

What I can see after a review, 
- All the png images works properly, so this should be a closed issue.
- For the *post* method in Action form, I created a dummy page for posting purposes (http://ptsv2.com/t/jasonelle). This page, always return a 200 code, if you call it correctly. So, in the login page, I referenced to it to get it work:

```
"url": "http://ptsv2.com/t/jasonelle/post",
"method": "post",
"data": {
  "email": "{{$get.email}}",
  "password": "{{$get.password}}"
}
``` 

To get this work properly, you need to put in the AndroidManifest.xml the next option (take a look at [this](https://stackoverflow.com/questions/45940861/android-8-cleartext-http-traffic-not-permitted?answertab=votes#tab-top))

```
<application
        android:name=".Launcher.Launcher"
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:supportsRtl="true"
        android:usesCleartextTraffic="true"
        android:theme="@style/AppTheme">
```

I think the problem is that you aren't getting to your host, from your device to your localhost server. Tell me if this [jason](https://base.jasonelle.com/items/d12329cc/) works for you.

**Comment by andresberejnoi** [comment] 2019-11-27 07:47
Thank you so much. After about a month of hitting my head against the wall It's finally working! It was simply the line `android:usesCleartextTraffic="true"` missing from AndroidManifest.xml that I needed. I added it to the file and now my requests get sent. I had never dealt with Android Studio before so did not know I needed something like that. Just for curiosity, from the link to Stackoverflow what I gather is that I would not have had this problem if I were using https instead of http, right?

The last thing I would ask if you could help with is in the part of in-line javascript functions. I don't know if they had anything to do with the previous problem. But if it is a simple answer maybe it could go here. I might ask another question about more specific case.

I am trying to login to a service (more specifically to a Traccar server) and since I could not get $session.set to work (most likely do to my own mistakes), I was trying to maintain state with the server using standard http authorization in each API call in the following way:

```
"type":"$network.request",
    "options": {
        "url":"http://some_dummy_server/auth",
        "method":"get",
        "header":{
            "Authorization":"Basic {{btoa($global.email:$global.password)}}",
        }
    },
    "success":{
        "type":"$cache.set",
        "options":{
            "items":"{{$jason}}"
        },
        "success":{
            "type":"$util.alert",
            "options":{
                "title":"Location fetched",
                "description":"{{$cache.items.latitude}},{{$cache.items.longitude}}"
            }
        }
    },
    "error":{
        "type":"$util.banner",
        "options":{
            "title":"Error Occurred",
            "description":"Error
        }
    }
```

Notice how on the request's header I am using a built-in javascript function `btoa` which should encode the strings I am giving it as parameters. When I make a request in this style, what I get in the headers is the literal string that I typed `"{{btoa($global.email:$global.password)}}"` instead of the function being evaluated. I also tried using the function `JSON.stringify` since I saw it on one example in the docs and got the literal text as well.

 The Traccar session documentation is at [https://www.traccar.org/traccar-api/](https://www.traccar.org/traccar-api/). It says that there are two authorization options. One of them is the one I am trying: standard http authorization. The other one is using a session api endpoint and I assume I can somehow use this method with $session.set from Jasonelle. The description for Traccar session api is [here](https://www.traccar.org/api-reference/#path--session).

The reasons I was confused with using $session action is that I am not sure how I'm supposed to turn Traccar's response from their endpoint /api/session (link above) to create a cookie or something that Jasonelle should store. 

If this is too long of a stretch for this thread then should I ask this again as support or issue (because of the in-line javascript problem)?

Thanks for all the help

**Comment by clsource** [comment] 2019-11-27 13:12
Hello @andresberejnoi I'm closing this since it seems the original issue was solved. About the scripts that returns `{{JSON.stringify()}}` that could happend in two scenarios. The first one is that you are not executing the scripts inside the `templates` section. The second scenario is that the inline script returns undefined or an error, if that happens then the behaviour is to consider it as a string and returns the literal you got.

https://jasonelle.com/jasonette-old-docs/templates/

Thanks 👍

**Closed as completed by clsource** 2019-11-27 13:12 UTC
Labels: jasonette-android
